name: Release Notes Generator

on: 
    push:
        branches:
            - 'v*'
    workflow_dispatch:

jobs:
    draft-release-notes:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Draft release notes
              uses: release-drafter/release-drafter@v5
              env: 
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}